language: python
python:
  - "2.7"
dist: trusty
script: 
  - python setup.py install 
deploy:
  provider: pypi
  user: atmosphere
  password:
    secure: RpKQdpwtHPtS2NBE1J/VkwA98I1GPWCXAbsviScYuaDvqDmGsbMRvo4yp4/luza3iSJJVw+HR+GjmN2S0F++k9nHRLoBGjyLs0FWSUw0P0wsVq2A9+hpgLbxygBoLD5Q7RhxqVHoIabmalgIN7qBUU4wMG/PULRNGGxKkorghdU=
  on:
    tags: true
